version: "3.9"
services:
  resolver:
    build:
      context: ./.
      target: flask
    networks:
      - solr
      - nginx
    environment:
      - FLASK_APP=flask_app.resolver:app
    env_file:
      ./.env.conf
    restart: unless-stopped

  sp_cache:
    build:
      context: ./.
      target: flask
    networks:
      - solr
      - nginx
    environment:
      - FLASK_APP=flask_app.sp_cache:app
    env_file:
      ./.env.conf
    restart: unless-stopped
    volumes:
      - "scratch-path:/scratch-path"

  solr:
    image: solr:8.10.1-slim
    networks:
      - solr
    environment:
      # See https://github.com/docker-solr/docker-solr/issues/273
      - SOLR_OPTS=-XX:-UseLargePages
    entrypoint:
      # See https://github.com/docker-solr/docker-solr/issues/188
      - bash
      - "-c"
      - "precreate-core sp_collections /opt/solr/server/solr/sp_collections/conf; precreate-core spcoco /opt/solr/server/solr/spcoco/conf; precreate-core specimen_records /opt/solr/server/solr/specimen_records/conf; exec solr -f"
    volumes:
      - './solr_cores/:/opt/solr/server/solr'
      - 'solr:/var/solr'

  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    depends_on:
      - resolver
      - sp_cache
    networks:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./static/:/var/www/:ro"
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./config/fullchain.pem:/etc/letsencrypt/fullchain.pem:ro"
      - "./config/privkey.pem:/etc/letsencrypt/privkey.pem:ro"

volumes:
  scratch-path:
  solr:

networks:
  solr:
  nginx:
